# Generated by Django 3.1.14 on 2024-08-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20240822_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ownership_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Partnership', 'Partnership'), ('Corporation', 'Corporation'), ('Other', 'Other')], default='Other', max_length=255),
        ),
    ]
