# Generated by Django 3.1.14 on 2024-08-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_business_ownership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='num_employees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='num_pumps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='num_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='num_trucks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
