# Generated by Django 3.1.14 on 2024-08-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20240823_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_industry',
            field=models.CharField(choices=[('Energy', 'Energy'), ('Construction', 'Construction'), ('Hospitality', 'Hospitality'), ('Information', 'Information'), ('Manufacturing', 'Manufacturing'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Finance', 'Finance'), ('Insurance', 'Insurance'), ('Transportation', 'Transportation'), ('Other', 'Other')], default='Other', max_length=255),
        ),
    ]
