# Generated by Django 3.1.14 on 2024-08-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_business_corp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='corp_type',
            field=models.CharField(choices=[('Energy', 'Energy'), ('Construction', 'Construction'), ('Hospitality', 'Hospitality'), ('Information', 'Information'), ('Manufacturing', 'Manufacturing'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Finance', 'Finance'), ('Insurance', 'Insurance'), ('Transportation', 'Transportation'), ('Other', 'Other')], default='N/A', max_length=255),
        ),
    ]
