# Generated by Django 3.1.14 on 2024-08-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20240823_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='corp_type',
            field=models.CharField(choices=[('S-Corp', 'S-Corp'), ('C-Corp', 'C-Corp'), ('N/A', 'N/A')], default='N/A', max_length=255),
        ),
    ]
