# Generated by Django 3.1.14 on 2024-08-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20240823_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='avg_inventory',
            new_name='Average Inventory Amount ($)',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_industry',
            new_name='Business Industry',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='corp_type',
            new_name='Corporation Type',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='num_employees',
            new_name='Number of Employees',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='num_pumps',
            new_name='Number of Pumps',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='num_seats',
            new_name='Number of Seats',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='num_trucks',
            new_name='Number of Trucks',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='ownership_type',
            new_name='Ownership Type',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='sqft',
            new_name='SQFT',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='wholesale_retail',
            new_name='Wholesale or Retail',
        ),
    ]
