# Generated by Django 3.1.14 on 2024-08-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20240826_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='Business Industry',
            field=models.CharField(choices=[('Energy', 'Energy'), ('Construction', 'Construction'), ('Hospitality', 'Hospitality'), ('Information', 'Information'), ('Manufacturing', 'Manufacturing'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Finance', 'Finance'), ('Insurance', 'Insurance'), ('Transportation', 'Transportation'), ('Law', 'Law'), ('Other', 'Other')], default='Other', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='SQFT',
            field=models.PositiveIntegerField(default=0, help_text='Square footage of workspace'),
        ),
    ]
