# Generated by Django 3.1.14 on 2024-08-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20240827_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='Filing Type',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='Status',
            field=models.CharField(default='A', max_length=255),
        ),
    ]
