# Generated by Django 3.1.14 on 2024-08-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20240827_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Average Inventory Amount ($)',
            new_name='avg_inventory',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='Business Industry',
            new_name='business_industry',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='Corporation Type',
            new_name='corp_type',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='Number of Employees',
            new_name='num_employees',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='Number of Pumps',
            new_name='num_pumps',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='Number of Seats',
            new_name='num_seats',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='Number of Trucks',
            new_name='num_trucks',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='Ownership Type',
            new_name='ownership_type',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='SQFT',
            new_name='sqft',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='Wholesale or Retail',
            new_name='wholesale_retail',
        ),
    ]
