# Generated by Django 3.1.14 on 2024-08-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_business_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(default=' ', help_text='Enter the email you would like communication sent to', max_length=254),
        ),
    ]
