# Generated by Django 3.1.14 on 2024-08-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20240828_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
