# Generated by Django 3.1.14 on 2024-09-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_business_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='drivers_license',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
