# Generated by Django 3.1.14 on 2024-09-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_business_drivers_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='drivers_license',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
