# Generated by Django 3.1.14 on 2024-09-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_auto_20240902_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='drivers_license',
            field=models.FileField(blank=True, null=True, upload_to='drivers-licenses/'),
        ),
    ]
