# Generated by Django 3.1.14 on 2024-09-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20240902_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='avg_inventory',
            new_name='Average_Inventory_Value',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_industry',
            new_name='Business_Industry',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='corp_type',
            new_name='Corporation_Type',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='num_employees',
            new_name='Number_of_Employees',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='num_pumps',
            new_name='Number_of_Pumps',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='num_seats',
            new_name='Number_of_Seats',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='num_trucks',
            new_name='Number_of_Trucks',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='ownership_type',
            new_name='Ownership_Type',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='sqft',
            new_name='Squarefootage_of_Workspace',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='wholesale_retail',
            new_name='Wholesale_or_Retail',
        ),
    ]
