# Generated by Django 3.1.14 on 2024-09-19 20:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0022_auto_20240902_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Business Tax Receipt Invoice', max_length=255)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='V1QuickInvoicesRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(default='email@domain.com', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='BTR Invoice Title', max_length=64)),
                ('due_date', models.DateField(default=datetime.date(2024, 12, 31))),
                ('allow_overpayment', models.BooleanField(default=False)),
                ('bank_funded_only_override', models.BooleanField(default=True)),
                ('allow_partial_payment', models.BooleanField(default=False)),
                ('amount_due', models.FloatField(default=0.0)),
                ('item_header', models.CharField(default='Item Header', max_length=255)),
                ('item_footer', models.CharField(default='Item Footer', max_length=255)),
                ('notification_days_before_due_date', models.IntegerField(default=3)),
                ('notification_days_after_due_date', models.IntegerField(default=7)),
                ('send_text_to_pay', models.BooleanField(default=True)),
                ('Cell_Phone', models.CharField(default='123-456-7890', max_length=10)),
                ('notification_on_due_date', models.BooleanField(default=True)),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.business')),
                ('item_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.itemlist4')),
            ],
        ),
    ]
