# Generated by Django 3.1.14 on 2024-06-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('budget_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
