# Generated by Django 3.1.14 on 2024-06-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0002_auto_20240614_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='amount',
            field=models.FloatField(max_length=2),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='budget_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense - Variable', 'Expense - Variable'), ('Expense - Fixed', 'Expense - Fixed')], max_length=255),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
