# Generated by Django 3.1.14 on 2024-06-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0003_auto_20240615_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='date',
            field=models.DateField(blank=True, default='N/A', null=True),
        ),
    ]
