# Generated by Django 3.1.14 on 2024-06-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0004_auto_20240615_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedExpenseLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.FloatField(max_length=2)),
                ('date', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.FloatField(max_length=2)),
                ('date', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VariableExpenseLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('starting_amount', models.FloatField(max_length=2)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount_left', models.FloatField(max_length=2)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='budget_type',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='title',
        ),
    ]
