# Generated by Django 3.1.14 on 2024-06-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0006_auto_20240615_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variableexpense',
            name='date',
        ),
    ]
