# Generated by Django 3.1.14 on 2024-06-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0007_remove_variableexpense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedexpense',
            name='amount',
            field=models.FloatField(),
        ),
    ]
