# Generated by Django 3.1.14 on 2024-06-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0009_auto_20240617_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
