# Generated by Django 3.1.14 on 2024-06-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0010_auto_20240617_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedexpense',
            name='amount',
            field=models.FloatField(),
        ),
    ]
