# Generated by Django 3.1.14 on 2024-06-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0011_auto_20240617_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='variableexpense',
            name='amount_left',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='variableexpense',
            name='starting_amount',
            field=models.FloatField(),
        ),
    ]
