# Generated by Django 3.1.14 on 2024-06-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0012_auto_20240617_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variableexpense',
            name='paid',
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('associated_variable_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_item.variableexpense')),
            ],
        ),
    ]
