# Generated by Django 3.1.14 on 2024-06-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0014_spending_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='date',
            field=models.DateField(),
        ),
    ]
