# Generated by Django 3.1.14 on 2024-06-22 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0015_auto_20240617_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variableexpense',
            name='amount_left',
        ),
    ]
