# Generated by Django 3.1.14 on 2024-06-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0019_auto_20240624_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='asset_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Real Estate', 'Real Estate'), ('Property', 'Property')], max_length=255),
        ),
    ]
