# Generated by Django 3.1.14 on 2024-06-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0020_auto_20240624_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assets',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spending',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
