# Generated by Django 3.1.14 on 2024-06-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0021_auto_20240624_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
