# Generated by Django 3.1.14 on 2024-08-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0022_auto_20240624_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='asset_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Real Estate', 'Real Estate'), ('Property', 'Property'), ('Retirement Account', 'Retirement Account')], max_length=255),
        ),
    ]
